name: 'Configure AWS credentials and setup Terraform'
description: 'This is a composite action that configures AWS credentials and sets up Terraform.'
inputs:
    aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
    aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
    aws-region:
        description: 'AWS Region'
        required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4
        terraform_wrapper: false

    - name: Configure Terraform plugin cache
      shell: bash
      run: |
        echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
        mkdir --parents "$HOME/.terraform.d/plugin-cache"

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          terraform-${{ runner.os }}-