name: Backend CI Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  development_ci_job:
    runs-on: ubuntu-latest
    environment: development

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create .env file
        run: |
          touch .env
          echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ env.DB_NAME }}" >> .env
      - name: Wait for MySQL to initialize
        run: |
          for i in {1..10}; do
            nc -z 127.0.0.1 3306 && echo "MySQL is accepting connections!" && break
            echo "Waiting for MySQL to accept connections..."
            sleep 5
          done
      - name: Run Unit Tests with pytest
        run: |
          pytest ./tests/services/ -W ignore::DeprecationWarning
      - name: Run Integration Tests with pytest
        run: |
          pytest ./tests/routes/ -W ignore::DeprecationWarning